import type { Metadata } from "next";
import { Mulish, Cabin } from "next/font/google";
import "./globals.css";

const mulish = Mulish({ subsets: ["latin"] });
const cabin = Cabin({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mulish.className + cabin.className}>{children}</body>
    </html>
  );
}
